artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/NedRaph/Neural-Network-model-for-Chicken-Disease-Classification/raw/refs/heads/main/Chicken-fecal-images%20(1).zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion